### ISSUE TITLE
Calendar entry cannot be updated for a loaned item

### ISSUE THREAD

**Issue by shsr** [stovocor/whohasmystuff#16]
• Open “Who Has My  Stuff?” app
• Tap on “Add new lend item” option
• Create new lend item with “Add Entry to Calendar”
• Tap on  “Edit” option for loaned item
• Check whether “Calendar entry” can be edited

Expected: Calendar entry should still be retained for loaned item
Actual: “Add Entry to Calendar” was no longer available for any loaned item

**Comment by stovocor** [comment]
No feedback for more than two years, closing this issue.
