### ISSUE TITLE
[external] File not found errors in F-Droid

### ISSUE THREAD

**Issue by generalmanager** [stovocor/whohasmystuff#20]
When I try downloading any of the three available versions via the F-Droid app, I get file not found errors. Downloading them from the F-Droid website works tough.
The device is on 4.4.4 and I don't have those problems with other apps.

If you need more information to resolve this, I'm happy to help.

**Comment by stovocor** [comment]
I just tested the installation of 1.0.24 with F-Droid, works perfectly fine for me.

Since this is not an issue of my app, could you report the problem for F-Droid, please?

**Comment by stovocor** [comment]
No response in two years, so I am closing this issue. Please feel free to open a new one if the problem persists.
