### ISSUE TITLE
Missing Crowdin link

### ISSUE THREAD

**Issue by Roboe** [stovocor/whohasmystuff#26]
Where can we contribute translations? It seems `string.xml` are generated by Crowdin, but no Crowdin link is supplied.

A "Translation" section could be appended to the `README.md` or on a separated `CONTRIBUTING.md` file.

**Comment by stovocor** [comment]
The link to Crowdin is provided in the [Play Store entry](https://play.google.com/store/apps/details?id=de.freewarepoint.whohasmystuff). However, you are totally right and I will add it to the README as well.

**Comment by Roboe** [comment]
Great! :)
